r <- structure(list(url = "http://api.vipunen.fi/api/resources/suoritteet", status_code = 401L,
    headers = structure(list(date = "Sat, 16 Feb 2019 17:18:33 GMT",
        server = "Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips",
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block",
        `cache-control` = "no-cache, no-store, max-age=0, must-revalidate",
        pragma = "no-cache", expires = "0", `content-type` = "application/json;charset=UTF-8",
        `content-encoding` = "gzip", vary = "Accept-Encoding",
        `transfer-encoding` = "chunked"), class = c("insensitive",
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1",
        headers = structure(list(date = "Sat, 16 Feb 2019 17:18:33 GMT",
            server = "Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips",
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block",
            `cache-control` = "no-cache, no-store, max-age=0, must-revalidate",
            pragma = "no-cache", expires = "0", `content-type` = "application/json;charset=UTF-8",
            `content-encoding` = "gzip", vary = "Accept-Encoding",
            `transfer-encoding` = "chunked"), class = c("insensitive",
        "list")))), cookies = structure(list(domain = logical(0),
        flag = logical(0), path = logical(0), secure = logical(0),
        expiration = structure(numeric(0), class = c("POSIXct",
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"),
    content = charToRaw("[\"FOo\"]"),
    # Manually added

    date = structure(1550337513, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000227,
    connect = 0.013748, pretransfer = 0.013815, starttransfer = 0.030058,
    total = 0.030976)), class = "response")
